### ISSUE TITLE
关于 yande 无法连接访问的问题

### ISSUE THREAD

**Issue by V1046-R** [usaginya/MoeLoader-Delta#100]
选择yande，点击搜索后
「
错误：请求被终止：未能创建 SSL/TLS 安全通道。
获取图片：<默认搜索>
站点名称：yande.re
当前页码：1 每页数量：50
代理模式：Custom
」
不知道是自己电脑的问题还是什么情况。
用其他电脑也会偶有发生的情况，但是大部分情况下可以正常连接。用的相同的VPN，相同的客户端，皆为Win7.

请教是哪里的设置出了问题，请求帮助，万分感谢。

**Comment by usaginya** [comment]
可能是代理的问题、也可能是系统的问题、Win7系统有一些SSL连接无法正确验证、就会提示SSL/TLS不能创建的错误
解决办法：
1. 换一种代理试试
2. 使用 Win7 以上的系统、比如Win10系统有对新的SSL3连接进行有效验证、可以解决这个问题

这里使用相同的方式搜索yande站点进行测试、可以正常加载

**Comment by V1046-R** [comment]
> Win7系统有一些SSL连接无法正确验证

好的，我再尝试寻找一下本机的问题。
