### ISSUE TITLE
求助，关于一窍不通的新人该怎么使用这款软件啊。

### ISSUE THREAD

**Issue by Peter237** [usaginya/MoeLoader-Delta#125]
我现在用的网是学校里电信的闪讯，打开软件默认设置后开始搜图，发现
![U){LFG_HLE1}%AGUBGO1Q](https://user-images.githubusercontent.com/73726713/124688125-d454ed00-df08-11eb-9711-2346a8ef161a.png)
![MXG3)}B6O%IHVL8_N01I0$W](https://user-images.githubusercontent.com/73726713/124688224-ffd7d780-df08-11eb-8c21-017a5dad7e5c.png)
![}WOJ~(ZIFX`YH3~ZAYQ%)T5](https://user-images.githubusercontent.com/73726713/124688381-3dd4fb80-df09-11eb-90f1-77e4c5f04dba.png)
类似的还很多，需要账号登陆的搜不了就算了，发现除konachan等零星几个网站外，其他都搜图失败。用手机移动开热点发现连konachan都用不了了。在网上也没搜到这个软件的使用教程什么的，能不能指点一下新人该怎么用这款软件。

**Comment by usaginya** [comment]
> 我现在用的网是学校里电信的闪讯，打开软件默认设置后开始搜图，发现
> ![U){LFG_HLE1}%AGUBGO1Q](https://user-images.githubusercontent.com/73726713/124688125-d454ed00-df08-11eb-9711-2346a8ef161a.png)
> ![MXG3)}B6O%IHVL8_N01I0$W](https://user-images.githubusercontent.com/73726713/124688224-ffd7d780-df08-11eb-8c21-017a5dad7e5c.png)
> ![}WOJ~(ZIFX`YH3~ZAYQ%)T5](https://user-images.githubusercontent.com/73726713/124688381-3dd4fb80-df09-11eb-90f1-77e4c5f04dba.png)
> 类似的还很多，需要账号登陆的搜不了就算了，发现除konachan等零星几个网站外，其他都搜图失败。用手机移动开热点发现连konachan都用不了了。在网上也没搜到这个软件的使用教程什么的，能不能指点一下新人该怎么用这款软件。

* 一些站点需要搭梯才能搜索得到图片信息、在设定中设好代理就能搜索大部分站点的图片
* 在SitePacks文件夹中新建18x.txt文件可以多几个站点、个别站点有比较新的验证方式、因系统不同可能会不能使用
* mjv-art的站点是解析原图地址失败了所以才加载失败、等有空再修

**Comment by Peter237** [comment]
> 
> 
> > 我现在用的网是学校里电信的闪讯，打开软件默认设置后开始搜图，发现
> > ![U){LFG_HLE1}%AGUBGO1Q](https://user-images.githubusercontent.com/73726713/124688125-d454ed00-df08-11eb-9711-2346a8ef161a.png)
> > ![MXG3)}B6O%IHVL8_N01I0$W](https://user-images.githubusercontent.com/73726713/124688224-ffd7d780-df08-11eb-8c21-017a5dad7e5c.png)
> > ![}WOJ~(ZIFX`YH3~ZAYQ%)T5](https://user-images.githubusercontent.com/73726713/124688381-3dd4fb80-df09-11eb-90f1-77e4c5f04dba.png)
> > 类似的还很多，需要账号登陆的搜不了就算了，发现除konachan等零星几个网站外，其他都搜图失败。用手机移动开热点发现连konachan都用不了了。在网上也没搜到这个软件的使用教程什么的，能不能指点一下新人该怎么用这款软件。
> 
>     * 一些站点需要搭梯才能搜索得到图片信息、在设定中设好代理就能搜索大部分站点的图片
> 
>     * 在SitePacks文件夹中新建18x.txt文件可以多几个站点、个别站点有比较新的验证方式、因系统不同可能会不能使用
> 
>     * mjv-art的站点是解析原图地址失败了所以才加载失败、等有空再修

**Comment by Peter237** [comment]
好的，非常感谢
