### ISSUE TITLE
建议重写一个安全文件名函数替换ToSafeString()

### ISSUE THREAD

**Issue by rorschach-py** [usaginya/MoeLoader-Delta#31]
使用Chrome IE11等浏览器下载名称中包含斜杠/的图片时会将斜杠替换为下划线，而MoeLoader则是移除斜杠，这会影响到类似 fate/stay night 之类的标签。当混合使用浏览器和MoeLoader时，标签名称不一致会导致排除重复文件困难。

**Comment by usaginya** [comment]
只是ReplaceInvalidPathChars方法中的替换问题、与ToSafeString方法无关、ToSafeString方法没有对路径中非法字符处理的功能。现已将非法字符改为替换成下划线

**Comment by rorschach-py** [comment]
原来是这个，看代码不仔细了 -_-!!
