### ISSUE TITLE
v7.0.6.0 Release 运行后无站点可选

### ISSUE THREAD

**Issue by CainSakura** [usaginya/MoeLoader-Delta#47]
以下是 `SitePacks\site_error.log` 文件中的内容。

```
[异常站点]: 站点载入过程
[异常时间]: 2018/9/29 6:53:41
[异常信息]: 尝试从一个网络位置加载程序集，在早期版本的 .NET Framework 中，这会导致对该程序集进行沙盒处理。此发行版的 .NET Framework 默认情况下不启用 CAS 策略，因此，此加载可能会很危险。如果此加载不是要对程序集进行沙盒处理，请启用 loadFromRemoteSources 开关。有关详细信息，请参见 http://go.microsoft.com/fwlink/?LinkId=155569。
[异常对象]: mscorlib
[调用堆栈]: 在 System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   在 System.Reflection.Assembly.LoadFile(String path)
   在 MoeLoaderDelta.SiteManager..ctor()
[触发方法]: System.Reflection.RuntimeAssembly nLoadFile(System.String, System.Security.Policy.Evidence)
```

**Comment by usaginya** [comment]
@CainSakura 下个版本尝试另一种加载方法、暂时先试将目录下的 MoeLoaderDelta.exe.config 内容替换为下面的内容再尝试运行

`<?xml version="1.0"?>`
`<configuration>`
`<startup useLegacyV2RuntimeActivationPolicy="true"><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.1"/></startup>`
`  <runtime>`
`    <gcConcurrent enabled="true" />`
`    <loadFromRemoteSources enabled="true"/>`
`    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">`
`      <publisherPolicy apply="yes" />`
`      <probing privatePath="lib" />`
`    </assemblyBinding>`
`  </runtime>`
`</configuration>`

**Comment by CainSakura** [comment]
@usaginya 替换后可以正常使用了，非常感谢。
