### ISSUE TITLE
V7.0.6.1 批量添加pixiv站点图片下载任务时可能导致程序卡死问题

### ISSUE THREAD

**Issue by Mrodot** [usaginya/MoeLoader-Delta#51]
RT，在批量添加下载任务时会卡顿。严重时会导致程序无响应，并且内存占用一直增加。

V7.0.6.1

**Comment by usaginya** [comment]
@Mrodot 具体是添加了多少条下载任务呢？如果一次性添加太多下载任务、可能会因为列表项增加和统计、导致内存增加以及无响应的问题。

**Comment by Mrodot** [comment]
@usaginya 一次最多添加3、4张，应该不是一次性添加太多。。程序刚打开的时候是正常的，随着后面已下载的图片数量增加(大概50张左右)，添加一条下载任务都会卡很久。

**Comment by MaxMadcc** [comment]
@Mrodot 请问具体是什么站点。。。

**Comment by Mrodot** [comment]
@MaxMadcc 貌似的确是和站点有关系。。yande与konachan下载时下载了100+图片也没有出现这个问题。目前只发现下载pixiv的图片时会出现卡顿。

**Comment by Mrodot** [comment]
V7.0.6.2 测试正常，感谢大佬修复~
