### ISSUE TITLE
Pixiv 无法搜索

### ISSUE THREAD

**Issue by vizmoe** [usaginya/MoeLoader-Delta#77]
[异常站点]: www.pixiv.net [IllustId]
[异常时间]: 2019/9/4 16:28:19
[异常信息]: 未将对象引用设置到对象的实例。
[异常对象]: SitePack
[调用堆栈]: 在 SitePack.SitePixiv.GetImages(String pageString, IWebProxy proxy)
[触发方法]: System.Collections.Generic.List`1[MoeLoaderDelta.Img] GetImages(System.String, System.Net.IWebProxy)

在搜索画师作品时，最多加载7张作品，且右击重试时只能短暂显示一瞬，无法根据作品 ID 搜索作品
测试画师ID：27452 作品ID：29172161
已右击登录网站

**Comment by usaginya** [comment]
@Syusyuly 搜索了哪个ID呢？

**Comment by vizmoe** [comment]
> @Syusyuly 搜索了哪个ID呢？

您好，已更新说明
测试画师ID：27452 作品ID：29172161

**Comment by usaginya** [comment]
@Syusyuly 测试是正常的、你可以尝试以下几个方法解决：
1. 更换代理服务器
2. 重新启动MLD、然后重新登录站点
3. 删除目录下配置文件Moe_config.ini
4. 重新下载MLD并更新到最新版本

**Comment by vizmoe** [comment]
感谢您的回复
在经过诸多尝试后，我发现可以通过 PID 搜索大多数图片，但上例中的 PID：29172161 与 UID：27452 无论如何都会报错，请问是否是因为没有清空相关缓存的问题呢？

**Comment by usaginya** [comment]
@Syusyuly 可能有点问题、到时候看看吧
