### ISSUE TITLE
自动登录失败

### ISSUE THREAD

**Issue by gfhghfghfh** [usaginya/MoeLoader-Delta#81]
右键菜单登录打开的浏览器中登录账号也没用 总是显示自动登录失败{"error"：false，"message"：""，"body"：{"validation_ errors"：

**Comment by usaginya** [comment]
@gfhghfghfh 在属性设置给予管理员权限、清空ie浏览器cookies或者重置ie浏览器设置、确保设置的代理和浏览器的一样、确定已登录到用户首页后再进行搜索试试
