### ISSUE TITLE
7.0.7.5极度不稳定，希望改进下

### ISSUE THREAD

**Issue by mikifuns** [usaginya/MoeLoader-Delta#99]
具体我没有崩溃日志，打开konachan后第一次放置一会后直接无响应，第二次任意勾选几张图片后也无响应，第三次随机选择几张图片后来这里编辑issue就可以看到窗口下直接无响应然后快速退出。而且新版本那个滚动真的是太快了，希望能改进下
已经回滚7.0.7.4，一切正常。

**Comment by usaginya** [comment]
@mikifuns 看看系统错误记录有没有关于mld的错误信息、有的话发上来看看

**Comment by mikifuns** [comment]
无法复现，暂关，再碰到的话另开新issue.
